
```{r, echo=FALSE}
library(htmltools)
```

```{r, echo=FALSE}
    div(class="row",
      div(class="col-sm-3",
        div(
          class="list-group",
          a(
            class="list-group-item",
            "ANOVA",
            href="anova"
          ),
          a(
            class="list-group-item",
            "Data Frames",
            href="data-frames"
          ),
          a(
            class="list-group-item",
            "Numerical Descriptives",
            href="numerical-descriptives"
          ),
          a(
            class="list-group-item",
            "Regression",
            href="regression"
          ),
          a(
            class="list-group-item",
            "t Tests",
            href="t-tests"
          )
        ),
      ),
      div(
        class="col-sm-9",
        h2("Psych Tutorials"),
        p("Welcome to the Psych R Tutorials collection. Here you can find links to tutorials. They are on the left sidebar, or, if you're using a small screen, they are above.")
      )
    )



```
