name: New Test Branch
run-name: ${{ github.actor }} is replacing test branch with new test branch 🚀
on:
  push:
    branches:
      - main
jobs:
  Recreate-Test-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by Github."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set git credentials
        run: |
            git config --global user.email "joehoskisson@gmail.com"
            git config --global user.name "Joe Hoskisson"
      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Create new test branch"
      - run: git checkout -b test
      - run: echo "Removing all files except those that start with '.' and those"
      - run: echo "that are in the _site directory and _site.yml"
      - run: find . -not -path "./.*" -a -not -path "./_site*" -delete
      - run: echo "remove _site.yml"
      - run: rm _site.yml
      - run: mv _site/* .
      - run: rm -r _site
      - run: git add .
      - run: git commit -m "build test branch"
      - name: force replacement of test branch in remote repository
        run: git push origin test --force
      - run: echo " This job's status is ${{job.status}}."